apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: test
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: test
    spec:
      containers:
        - args:
            - ./wait-for-it.sh
            - db:5432
            - --
            - nosetests
            - -s
            - --exe
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:password@db:5432/twitter_api_flask
            - name: FLASK_ENV
              value: test
          image: test
          name: test
          resources: {}
          volumeMounts:
            - mountPath: /code
              name: test-claim0
      restartPolicy: Always
      volumes:
        - name: test-claim0
          persistentVolumeClaim:
            claimName: test-claim0
status: {}
